services:
  - type: worker
    name: rename-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FFMPEG_MICRO_API_KEY_1
        sync: false
      - key: FFMPEG_MICRO_API_KEY_2
        sync: false
      - key: FFMPEG_MICRO_API_KEY_3
        sync: false
      - key: FFMPEG_MICRO_API_KEY_4
        sync: false
      - key: FFMPEG_MICRO_API_KEY_5
        sync: false
      - key: ALLOWED_USER_IDS
        sync: false
